// Regenerates netlify/lib/app-ui.mjs from app-source/tool.html.
// Run:  node build-ui.mjs      (after every edit to app-source/tool.html)
import { readFileSync, writeFileSync } from "node:fs";
const html = readFileSync(new URL("./app-source/tool.html", import.meta.url), "utf8");
writeFileSync(
  new URL("./netlify/lib/app-ui.mjs", import.meta.url),
  "// GENERATED by build-ui.mjs from app-source/tool.html — edit that file, not this one.\n" +
  "export default " + JSON.stringify(html) + ";\n"
);
console.log("app-ui.mjs written (" + html.length + " chars)");
